import * as icons from "~/lib/categories/icons";
import { translate } from "~/lib/i18n/utils/translator";

const culture = {
  culture: {
    name: () => translate("Culture"),
    icon: icons.theatre,
    synonyms: [
      "cultural_center",
      "Concert Hall",
      "Cultural Center",
      "Jazz Club",
      "200-2300-0022",
      "Kultur und Soziales",
    ],
  },

  museum: {
    name: () => translate("Museum"),
    icon: icons.museum,
    parents: ["culture", "leisure", "tourism", "education"],
    synonyms: [
      "tourism=museum",
      "museum",
      "Museum",
      "Art Museum",
      "History Museum",
      "Planetarium",
      "Science Museum",
      "Observatory",
      "Historic Site",
      "Children's Museum",
      "300-3100-0026",
      "300-3100-0027",
      "300-3100-0028",
      "300-3100-0029",
      "300-3100-0000",
      "Musée",
    ],
  },

  library: {
    name: () => translate("Library"),
    icon: icons.library,
    parents: ["culture"],
    synonyms: [
      "amenity=library",
      "library",
      "Library",
      "Other library",
      "800-8300-0000",
      "800-8300-0175",
      "Bibliothek",
    ],
  },

  arts_center: {
    name: () => translate("Arts center"),
    icon: icons.artGallery,
    parents: ["culture"],
    synonyms: [
      "amenity=arts_centre",
      "300-3000-0024",
      "800-8400-0176",
      "Art Studio",
      "Convention or Exhibition Centre",
      "Exhibit",
      "Gallery",
      "arts_centre",
      "cultural_center",
    ],
  },

  public_art: {
    name: () => translate("Artwork"),
    icon: icons.artGallery,
    parents: ["culture"],
    synonyms: [
      "tourism=artwork",
      "Outdoor Sculpture",
      "Public Art",
      "Sculpture Garden",
      "Street Art",
      "artwork",
    ],
  },

  art_gallery: {
    name: () => translate("Art Gallery"),
    icon: icons.artGallery,
    parents: ["culture"],
    synonyms: [
      "tourism=gallery",
      "Art Gallery",
      "Museum oder Galerie",
      "art_gallery",
      "gallery",
    ],
  },

  place_of_worship: {
    name: () => translate("Place Of Worship"),
    icon: icons.placeOfWorship,
    parents: ["culture"],
    synonyms: [
      "amenity=place_of_worship",
      "300-3200-0000",
      "300-3200-0030",
      "300-3200-0031",
      "300-3200-0032",
      "300-3200-0033",
      "300-3200-0034",
      "300-3200-0309",
      "300-3200-0375",
      "Ashram",
      "Buddhist Temple",
      "Cemetery",
      "Cemevi",
      "Church",
      "Confucian Temple",
      "Friedhof",
      "Gurdwara",
      "Hindu Temple",
      "Kingdom Hall",
      "Monastery",
      "Mosque",
      "Place of Worship",
      "Prayer Room",
      "Religious Place",
      "Religious School",
      "Shrine",
      "Spiritual Center",
      "Spiritualité",
      "Synagogue",
      "Temple",
      "Terreiro",
      "cemetery",
      "church",
      "hindu_temple",
      "mosque",
      "place_of_worship",
      "synagogue",
    ],
  },

  theater: {
    name: () => translate("Theater"),
    icon: icons.theatre,
    parents: ["culture"],
    synonyms: [
      "amenity=theatre",
      "200-2200-0000",
      "200-2200-0020",
      "Amphitheater",
      "College Theater",
      "Indie Theater",
      "Konzerthalle oder Oper oder Theatersaal",
      "Music & Culture",
      "Opera House",
      "Performing Arts Centre",
      "Performing Arts Venue",
      "Theater",
      "Theatre",
      "opera_house",
      "performing_arts_theater",
      "theatre",
    ],
  },
} as const;

export function getCulture() {
  return culture;
}
