import * as icons from "~/lib/categories/icons";
import { translate } from "~/lib/i18n/utils/translator";

const food = {
  food: {
    name: () => translate("Food & Drinks"),
    icon: icons.restaurant,
    priority: 20,
    synonyms: [
      "100-1000-0003",
      "700-7200-0253",
      "700-7200-0258",
      "700-7400-0139",
      "Banqueting Hall",
      "Catering & Food Services",
      "College Cafeteria",
      "Corporate Cafeteria",
      "Food Production",
      "Kuruyemişçi",
      "Restaurant oder Café oder Bar",
      "Ski Lodge",
      "Takeaway and/or Delivery",
      "catering_service",
      "food",
      "meal_delivery",
    ],
  },

  restaurant: {
    name: () => translate("Restaurant"),
    icon: icons.restaurant,
    parents: ["food"],
    selectors: ["amenity=restaurant"],
    synonyms: [
      "100-1000-0000",
      "100-1000-0001",
      "100-1000-0002",
      "100-1000-0005",
      "100-1000-0006",
      "100-1000-0008",
      "100-1000-0009",
      "100-1000-0230",
      "300-3000-0065",
      "Abruzzo Restaurant",
      "Acai House",
      "Acehnese Restaurant",
      "Afghan Restaurant",
      "African Restaurant",
      "Agriturismo",
      "Alsatian Restaurant",
      "American Restaurant",
      "Andhra Restaurant",
      "Anhui Restaurant",
      "Aosta Restaurant",
      "Apple Wine Pub",
      "Arepa Restaurant",
      "Argentinian Restaurant",
      "Ash and Haleem Place",
      "Asian Restaurant",
      "Australian Restaurant",
      "Austrian Restaurant",
      "Auvergne Restaurant",
      "Awadhi Restaurant",
      "BBQ Joint",
      "Baiano Restaurant",
      "Balinese Restaurant",
      "Basilicata Restaurant",
      "Basque Restaurant",
      "Bavarian Restaurant",
      "Beijing Restaurant",
      "Belarusian Restaurant",
      "Belgian Restaurant",
      "Bengali Restaurant",
      "Betawinese Restaurant",
      "Bistro",
      "Blini House",
      "Borek Place",
      "Bosnian Restaurant",
      "Bossam/Jokbal Restaurant",
      "Botanero",
      "Bougatsa Shop",
      "Brasserie",
      "Bratwurst Joint",
      "Brazilian Restaurant",
      "Breakfast Spot",
      "Breton Restaurant",
      "Buffet",
      "Bulgarian Restaurant",
      "Bunsik Restaurant",
      "Burgundian Restaurant",
      "Burmese Restaurant",
      "Burrito Place",
      "Cafeteria",
      "Cajun / Creole Restaurant",
      "Calabria Restaurant",
      "Cambodian Restaurant",
      "Campanian Restaurant",
      "Cantonese Restaurant",
      "Caribbean Restaurant",
      "Casual Dining",
      "Catalan Restaurant",
      "Caucasian Restaurant",
      "Central Brazilian Restaurant",
      "Ch'ti Restaurant",
      "Cha Chaan Teng",
      "Chaat Place",
      "Chettinad Restaurant",
      "Chinese Aristocrat Restaurant",
      "Chinese Breakfast Place",
      "Chinese Restaurant",
      "Churrascaria",
      "Cigkofte Place",
      "Colombian Restaurant",
      "Comfort Food Restaurant",
      "Corsican Restaurant",
      "Creperie",
      "Cretan Restaurant",
      "Cuban Restaurant",
      "Currywurst Joint",
      "Czech Restaurant",
      "Delicatessen",
      "Dhaba",
      "Dim Sum Restaurant",
      "Diner",
      "Dizi Place",
      "Donburi Restaurant",
      "Doner Restaurant",
      "Dongbei Restaurant",
      "Dosa Place",
      "Dumpling Restaurant",
      "Dutch Restaurant",
      "Eastern European Restaurant",
      "Emilia Restaurant",
      "Empada House",
      "Empanada Restaurant",
      "English Restaurant",
      "Estaminet",
      "Ethiopian Restaurant",
      "Falafel Restaurant",
      "Fast Food",
      "Filipino Restaurant",
      "Fine Dining",
      "Fish Taverna",
      "Fondue Restaurant",
      "Food",
      "Franconian Restaurant",
      "French Restaurant",
      "Friuli Restaurant",
      "Fujian Restaurant",
      "German Pop-Up Restaurant",
      "German Restaurant",
      "Gilaki Restaurant",
      "Gluten-free Restaurant",
      "Goan Restaurant",
      "Goiano Restaurant",
      "Gozleme Place",
      "Greek Restaurant",
      "Grilled Meat Restaurant",
      "Guizhou Restaurant",
      "Gujarati Restaurant",
      "Gukbap Restaurant",
      "Hainan Restaurant",
      "Hakka Restaurant",
      "Halal Restaurant",
      "Hawaiian Restaurant",
      "Hawker Centre",
      "Henan Restaurant",
      "Himalayan Restaurant",
      "Hong Kong Restaurant",
      "Hotpot Restaurant",
      "Huaiyang Restaurant",
      "Hubei Restaurant",
      "Hunan Restaurant",
      "Hungarian Restaurant",
      "Hyderabadi Restaurant",
      "Imperial Restaurant",
      "Indian Chinese Restaurant",
      "Indian Restaurant",
      "Indian Sweet Shop",
      "Indonesian Meatball Place",
      "Indonesian Restaurant",
      "Irani Cafe",
      "Israeli Restaurant",
      "Italian Restaurant",
      "Jain Restaurant",
      "Janguh Restaurant",
      "Japanese Curry Restaurant",
      "Japanese Restaurant",
      "Javanese Restaurant",
      "Jegaraki",
      "Jewish Restaurant",
      "Jiangsu Restaurant",
      "Jiangxi Restaurant",
      "Kaiseki BistroRestaurant",
      "Karnataka Restaurant",
      "Kebab Restaurant",
      "Kerala Restaurant",
      "Kofte Place",
      "Kokoreç Restaurant",
      "Korean Restaurant",
      "Kosher Restaurant",
      "Kumpir Restaurant",
      "Kumru Restaurant",
      "Kurdish Restaurant",
      "Kushikatsu Restaurant",
      "Labour Canteen",
      "Latin American Restaurant",
      "Lebanese Restaurant",
      "Ligurian Restaurant",
      "Lombard Restaurant",
      "Lyonese Bouchon",
      "Mac & Cheese Joint",
      "Macanese Restaurant",
      "Magirio",
      "Maharashtrian Restaurant",
      "Malay Restaurant",
      "Malga",
      "Manadonese Restaurant",
      "Manchu Restaurant",
      "Manti Place",
      "Marche Restaurant",
      "Mediterranean Restaurant",
      "Mexican Restaurant",
      "Meyhane",
      "Meze Restaurant",
      "Middle Eastern Restaurant",
      "Mineiro Restaurant",
      "Modern European Restaurant",
      "Modern Greek Restaurant",
      "Molecular Gastronomy Restaurant",
      "Molise Restaurant",
      "Mongolian Restaurant",
      "Monjayaki Restaurant",
      "Moroccan Restaurant",
      "Mughlai Restaurant",
      "Multicuisine Indian Restaurant",
      "Nabe Restaurant",
      "New American Restaurant",
      "Noodle House",
      "Norman Restaurant",
      "North Indian Restaurant",
      "Northeast Indian Restaurant",
      "Northeastern Brazilian Restaurant",
      "Northern Brazilian Restaurant",
      "Okonomiyaki Restaurant",
      "Ouzeri",
      "Padangnese Restaurant",
      "Paella Restaurant",
      "Pakistani Restaurant",
      "Palatine Restaurant",
      "Parsi Restaurant",
      "Pastelaria",
      "Patsa Restaurant",
      "Peking Duck Restaurant",
      "Pelmeni House",
      "Persian Restaurant",
      "Peruvian Restaurant",
      "Piadineria",
      "Pide Place",
      "Piedmontese Restaurant",
      "Pilavcı",
      "Polish Restaurant",
      "Portuguese Restaurant",
      "Poutine Place",
      "Provençal Restaurant",
      "Puglia Restaurant",
      "Punjabi Restaurant",
      "Rajasthani Restaurant",
      "Ramen Restaurant",
      "Restaurant",
      "Rhenisch Restaurant",
      "Romagna Restaurant",
      "Roman Restaurant",
      "Romanian Restaurant",
      "Russian Restaurant",
      "Salad Place",
      "Salvadoran Restaurant",
      "Samgyetang Restaurant",
      "Sandwich Place",
      "Sardinian Restaurant",
      "Satay Restaurant",
      "Savoyard Restaurant",
      "Scandinavian Restaurant",
      "Schnitzel Restaurant",
      "Scottish Restaurant",
      "Seafood Restaurant",
      "Shaanxi Restaurant",
      "Shabu-Shabu Restaurant",
      "Shandong Restaurant",
      "Shanghai Restaurant",
      "Shanxi Restaurant",
      "Sicilian Restaurant",
      "Silesian Restaurant",
      "Slovak Restaurant",
      "Snack Place",
      "Soba Restaurant",
      "Som Tum Restaurant",
      "Soup Place",
      "South American Restaurant",
      "South Indian Restaurant",
      "South Tyrolean Restaurant",
      "Southeastern Brazilian Restaurant",
      "Southern / Soul Food Restaurant",
      "Southern Brazilian Restaurant",
      "Southwestern French Restaurant",
      "Spanish Restaurant",
      "Sri Lankan Restaurant",
      "Steakhouse",
      "Sukiyaki Restaurant",
      "Sundanese Restaurant",
      "Sushi Restaurant",
      "Swabian Restaurant",
      "Swiss Restaurant",
      "Szechuan Restaurant",
      "Söğüş Place",
      "Tabbakhi",
      "Taco Place",
      "Taiwanese Restaurant",
      "Takoyaki Place",
      "Tantuni Restaurant",
      "Tapas Restaurant",
      "Tapiocaria",
      "Taqueria",
      "Tatar Restaurant",
      "Tempura Restaurant",
      "Tex-Mex Restaurant",
      "Thai Restaurant",
      "Theme Restaurant",
      "Tianjin Restaurant",
      "Tibetan Restaurant",
      "Tonkatsu Restaurant",
      "Trattoria/Osteria",
      "Trentino Restaurant",
      "Truck Stop",
      "Tsipouro Restaurant",
      "Turkish Home Cooking Restaurant",
      "Turkish Restaurant",
      "Tuscan Restaurant",
      "Udon Restaurant",
      "Udupi Restaurant",
      "Ukrainian Restaurant",
      "Umbrian Restaurant",
      "Unagi Restaurant",
      "Varenyky restaurant",
      "Vegetarian / Vegan Restaurant",
      "Veneto Restaurant",
      "Venezuelan Restaurant",
      "Vietnamese Restaurant",
      "Wagashi Place",
      "West-Ukrainian Restaurant",
      "Xinjiang Restaurant",
      "Yakitori Restaurant",
      "Yoshoku Restaurant",
      "Yucatecan Restaurant",
      "Yunnan Restaurant",
      "Zhejiang Restaurant",
      "restaurant",
      "Çöp Şiş Place",
    ],
  },

  canteen: {
    name: () => translate("Canteen"),
    icon: icons.restaurant,
    parents: ["food"],
    selectors: ["amenity=canteen"],
  },

  coffee: {
    name: () => translate("Cafe"),
    icon: icons.cafe,
    parents: ["food"],
    selectors: ["amenity=cafe"],
    synonyms: [
      "100-1000-0007",
      "100-1100-0000",
      "100-1100-0010",
      "700-7400-0285",
      "700-7900-0132",
      "Café",
      "Coffee & Tea",
      "Coffee Shop",
      "Corporate Coffee Shop",
      "Internet Cafe",
      "Kafenio",
      "Pet Café",
      "Transport Cafe/Services",
      "Turkish Coffeehouse",
      "cafe",
      "internet_cafe",
    ],
  },

  pub: {
    name: () => translate("Bar"),
    icon: icons.bar,
    parents: ["food"],
    selectors: ["amenity=pub"],
    synonyms: ["Apres Ski Bar", "Irish Pub", "Pub", "bar"],
  },

  fastfood: {
    name: () => translate("Fast Food"),
    icon: icons.fastFood,
    parents: ["food"],
    selectors: ["amenity=fast_food", "amenity=food_court"],
    synonyms: [
      "Burger Joint",
      "Fast Food Restaurant",
      "Fish & Chips Shop",
      "Food Court",
      "Food Stand",
      "Food Truck",
      "Fried Chicken Joint",
      "Friterie",
      "Gastropub",
      "Hot Dog Joint",
      "Juice Bar",
      "Pizza Place",
      "Street Food Gathering",
      "Wings Joint",
      "fast_food",
      "fast_food_restaurant",
      "meal_takeaway",
    ],
  },

  bar: {
    name: () => translate("Bar"),
    icon: icons.bar,
    parents: ["food", "leisure"],
    selectors: ["amenity=bar"],
    synonyms: [
      "200-2000-0000",
      "200-2000-0011",
      "200-2000-0012",
      "200-2000-0013",
      "200-2000-0014",
      "200-2000-0368",
      "300-3000-0350",
      "300-3000-0351",
      "Bar or Pub",
      "Bar",
      "Beach Bar",
      "Beer Bar",
      "Brewery",
      "Champagne Bar",
      "Club",
      "Cocktail Bar",
      "Cocktail Lounge",
      "Dance Hall or Studio",
      "Gay Bar",
      "Hookah Bar",
      "Hotel Bar",
      "Jazz Club",
      "Karaoke Bar",
      "Karaoke Box",
      "Karaoke",
      "Lounge",
      "Music Festival",
      "Music Venue",
      "Night Club",
      "Nightlife & Entertainment",
      "Nightlife Spot",
      "Nuit",
      "Piano Bar",
      "Rock Club",
      "Sake Bar",
      "Speakeasy",
      "Sports Bar",
      "Tiki Bar",
      "Whisky Bar",
      "Wine Bar",
    ],
  },

  icecream: {
    name: () => translate("Ice Cream Shop"),
    icon: icons.iceCream,
    parents: ["food"],
    selectors: ["amenity=ice_cream"],
    synonyms: ["Frozen Yogurt Shop", "Ice Cream Shop", "ice_cream"],
  },

  biergarten: {
    name: () => translate("Beer Garden"),
    icon: icons.beer,
    parents: ["food"],
    selectors: ["amenity=biergarten"],
    synonyms: ["Beer Garden"],
  },

  drinkingwater: {
    name: () => translate("Drinking Water"),
    icon: icons.drinkingWater,
    parents: ["food"],
    selectors: ["amenity=drinking_water"],
    synonyms: ["drinking_water"],
  },
} as const;

export function getFood() {
  return food;
}
