import * as icons from "~/lib/categories/icons";
import { translate } from "~/lib/i18n/utils/translator";

const leisure = {
  leisure: {
    name: () => translate("Leisure"),
    icon: icons.theatre,
    priority: 40,
    selectors: ["leisure=*"],
    synonyms: [
      "200-2000-0015",
      "200-2000-0016",
      "200-2000-0017",
      "200-2000-0018",
      "550-5510-0206",
      "700-7200-0270",
      "700-7400-0292",
      "800-8700-0296",
      "Amusement Arcade",
      "Arcade",
      "Betting Shop",
      "Bien-être",
      "Billiards",
      "Circus School",
      "Circus",
      "Clubhouse",
      "Comedy Club",
      "Entertainment & Recreation",
      "Entertainment Service",
      "Event School",
      "Event Space",
      "Event",
      "Festival",
      "Fishing Spot",
      "Gaming Cafe",
      "General Entertainment",
      "Gun Rang",
      "Laser Tag",
      "Line / Queue",
      "Live Entertainment or Music",
      "Loisir",
      "Lottery Ticket Sales",
      "Other Event",
      "Other Great Outdoors",
      "Outdoor Event Space",
      "Pachinko Parlor",
      "Paintball Field",
      "Parade",
      "Pool Hall",
      "Pool or Snooker",
      "Racecourse",
      "Recreation Centre",
      "Resort",
      "Rest Area",
      "Roller Rink",
      "Roof Deck",
      "Salsa Club",
      "Samba",
      "Skate Park",
      "Skating Rink",
      "Wellness Centre & Services",
      "circus",
    ],
  },

  outdoor_seating: {
    name: () => translate("Outdoor Seating"),
    icon: icons.highwayRestArea,
    parents: ["leisure"],
    selectors: ["leisure=outdoor_seating"],
  },

  dog_park: {
    name: () => translate("Dog Park"),
    icon: icons.dogPark,
    parents: ["leisure"],
    selectors: ["leisure=dog_park"],
    synonyms: ["Dog park", "Dog Run"],
  },

  shower: {
    name: () => translate("Shower"),
    icon: icons.toilet,
    parents: ["accommodation", "leisure", "public_transfer"],
    selectors: ["amenity=shower"],
    synonyms: ["shower"],
  },

  picnic_table: {
    name: () => translate("Picnic table"),
    icon: icons.highwayRestArea,
    parents: ["leisure", "tourism"],
    selectors: ["leisure=picnic_table"],
  },

  allotments: {
    name: () => translate("Allotments"),
    icon: icons.village,
    parents: ["leisure"],
    selectors: ["landuse=allotments"],
  },

  bbq: {
    name: () => translate("Barbecue"),
    icon: icons.bbq,
    parents: ["tourism", "leisure"],
    selectors: ["amenity=bbq"],
  },

  cinema: {
    name: () => translate("Cinema"),
    icon: icons.cinema,
    parents: ["leisure"],
    selectors: ["amenity=cinema"],
    synonyms: [
      "200-2100-0019",
      "Cinema",
      "Drive-in Theater",
      "Film Studio",
      "Indie Movie Theater",
      "Kino",
      "Movie Theater",
      "Multiplex",
      "movie_theater",
    ],
  },

  brothel: {
    name: () => translate("Brothel"),
    icon: icons.heart,
    parents: ["leisure"],
    selectors: ["amenity=brothel"],
    synonyms: ["200-2000-0306", "Adult Entertainment"],
  },

  massage: {
    name: () => translate("Massage Studio"),
    icon: icons.hospital,
    parents: ["leisure"],
    selectors: ["shop=massage"],
    synonyms: ["Bath House", "Massage Studio", "Spa", "spa"],
  },

  playground: {
    name: () => translate("Playground / Play equipment"),
    icon: icons.playground,
    parents: ["leisure"],
    selectors: ["leisure=playground", "playground=*"],
    synonyms: [
      "Indoor Play Area",
      "Playground",
      "Recreation Center",
      "recreation_center",
    ],
  },

  zoo: {
    name: () => translate("Zoo"),
    icon: icons.zoo,
    parents: ["leisure"],
    selectors: ["tourism=zoo"],
    synonyms: [
      "550-5520-0208",
      "550-5520-0209",
      "550-5520-0210",
      "550-5520-0211",
      "550-5520-0228",
      "Animal Park",
      "Aquarium",
      "Wild Animal Park",
      "Wildlife Sanctuary",
      "Zoo Exhibit",
      "Zoo",
      "aquarium",
      "zoo",
    ],
  },

  casino: {
    name: () => translate("Casino"),
    icon: icons.casino,
    parents: ["leisure"],
    selectors: ["amenity=casino"],
    synonyms: ["200-2300-0000", "200-2300-0021", "Casino", "casino"],
  },

  stripclub: {
    name: () => translate("Strip Club"),
    icon: icons.heart,
    parents: ["leisure"],
    selectors: ["amenity=stripclub"],
    synonyms: ["Strip Club"],
  },

  park: {
    name: () => translate("Park/Garden"),
    icon: icons.park,
    parents: ["leisure"],
    selectors: [
      "leisure=park",
      "leisure=garden",
      "amenity=park",
      "landuse=recreation_ground",
    ],
    synonyms: [
      "550-5510-0202",
      "550-5510-0204",
      "Botanical Garden",
      "Botanischer Garten",
      "Garden",
      "National Park",
      "Outdoor Recreation",
      "Park oder Friedhof",
      "Park or Recreation Ground",
      "Park",
      "Ranger Station",
      "national_park",
      "park",
    ],
  },

  water_ramp: {
    name: () => translate("Water Ramp"),
    icon: icons.slipway,
    parents: ["leisure"],
    synonyms: ["water_ramp"],
  },

  sauna: {
    name: () => translate("Sauna"),
    icon: icons.hotSpring,
    parents: ["leisure"],
    selectors: ["leisure=sauna"],
    synonyms: ["Sauna / Steam Room"],
  },

  nightclub: {
    name: () => translate("Night Club"),
    icon: icons.nightclub,
    parents: ["leisure"],
    selectors: ["amenity=nightclub"],
    synonyms: [
      "Ballroom",
      "Country Dance Club",
      "Dance Studio",
      "Dive Bar",
      "Nightclub",
      "Other Nightlife",
      "night_club",
    ],
  },

  communitycentre: {
    name: () => translate("Community Center"),
    icon: icons.circle, // TODO: find proper icon, there's a custom one
    parents: ["leisure"],
    selectors: ["amenity=community_centre"],
    synonyms: [
      "800-8100-0169",
      "800-8400-0000",
      "900-9200-0299",
      "Civic or Community Center",
      "Club House",
      "Collective Community",
      "Community Center",
      "Community College",
      "Convention Center",
      "Fair or Convention Facility",
      "Kongresshalle",
      "Kultursaal",
      "Meeting Room",
      "Social Club",
      "Turn-und Festhallen",
      "Wedding Hall",
      "city_hall",
      "community_centre",
    ],
  },
} as const;

export function getLeisure() {
  return leisure;
}
