import * as icons from "~/lib/categories/icons";
import { translate } from "~/lib/i18n/utils/translator";

const sport = {
  sport: {
    name: () => translate("Sports"),
    icon: icons.soccer,
    synonyms: [
      "800-8600-0000",
      "800-8600-0191",
      "800-8600-0197",
      "Bowling Green",
      "Cycle Studio",
      "Disc Golf",
      "Go Kart Track",
      "Martial Arts Dojo",
      "Mini Golf",
      "Sports Activities",
      "bowling_alley",
      "sport",
    ],
  },

  sports_center: {
    name: () => translate("Sports Center"),
    icon: icons.soccer,
    parents: ["sport"],
    selectors: [
      "leisure=sports_centre",
      "leisure=sports_hall",
      "leisure=fitness_centre",
    ],
    synonyms: [
      "550-5510-0203",
      "800-8600-0181",
      "800-8600-0183",
      "800-8600-0184",
      "800-8600-0185",
      "800-8600-0188",
      "800-8600-0190",
      "800-8600-0192",
      "800-8600-0193",
      "800-8600-0194",
      "800-8600-0199",
      "800-8600-0200",
      "800-8600-0314",
      "800-8600-0376",
      "800-8600-0377",
      "Athletics & Sports",
      "BMX Track",
      "Badminton",
      "Basketball Court",
      "Basketball",
      "Bike Park",
      "Bowling Alley",
      "Boxing Gym",
      "Climbing Gym",
      "College Gym",
      "College Rec Center",
      "Fitness or Health Club",
      "Golf Course",
      "Golf Practice Range",
      "Gym / Fitness Center",
      "Gym",
      "Gymnastics Gym",
      "Ice Skating Rink",
      "Indoor Skiing",
      "Indoor Sports",
      "Outdoor Gym",
      "Pilates Studio",
      "Public Sports Facility",
      "Rock Climbing Spot",
      "Rugby",
      "Shooting Gallery",
      "Ski Area",
      "Ski Chairlift",
      "Ski Trail",
      "Skydiving Drop Zone",
      "Sporthalle",
      "Sports Club",
      "Sports Facility or Venue",
      "Squash Court",
      "Squash Facility",
      "Tennis Club",
      "Volleyball Court",
      "Yoga Studio",
      "fitness_center",
      "gym",
      "sports_centre",
      "sports_complex",
    ],
  },

  stadium: {
    name: () => translate("Stadium"),
    icon: icons.stadium,
    parents: ["sport"],
    selectors: ["leisure=stadium"],
    synonyms: [
      "800-8600-0180",
      "800-8600-0186",
      "800-8600-0187",
      "800-8600-0195",
      "800-8600-0381",
      "Baseball Stadium",
      "Basketball Stadium",
      "College Baseball Diamond",
      "College Basketball Court",
      "College Cricket Pitch",
      "College Hockey Rink",
      "College Stadium",
      "College Track",
      "Cricket Ground",
      "Curling Ice",
      "Eisstadion",
      "Football Stadium",
      "Golf Driving Range",
      "Hockey Arena",
      "Hockey Field",
      "Hockey Rink",
      "Ice Hockey",
      "Racetrack",
      "Racquetball Court",
      "Rugby Stadium",
      "Running Track",
      "Soccer Stadium",
      "Sports Complex or Stadium",
      "Sportstadion",
      "Stadium",
      "Tennis Stadium",
      "Track Stadium",
      "Track",
      "stadium",
    ],
  },

  soccer: {
    name: () => translate("Playing Field"),
    icon: icons.soccer,
    parents: ["sport"],
    selectors: ["leisure=pitch"],
    synonyms: [
      "800-8600-0189",
      "Badminton Court",
      "Baseball Field",
      "College Football Field",
      "College Soccer Field",
      "College Tennis Court",
      "Football pitch",
      "Outdoors & Recreation",
      "Soccer Field",
      "Tennis Court",
      "pitch",
    ],
  },

  swimming: {
    name: () => translate("Swimming Pool"),
    icon: icons.swimming,
    parents: ["sport"],
    selectors: ["amenity=swimming_pool", "leisure=swimming_pool"],
    synonyms: [
      "public_swimming_pool",
      "550-5520-0357",
      "800-8600-0182",
      "800-8600-0316",
      "Bathing Area",
      "Dive Spot",
      "Diving Centre",
      "Gym Pool",
      "Hotel Pool",
      "Pool",
      "Schwimmbad",
      "Swim School",
      "Swimming Pool",
      "Water Park",
      "swimming_pool",
    ],
  },
} as const;

export function getSport() {
  return sport;
}
