import * as icons from "~/lib/categories/icons";
import { translate } from "~/lib/i18n/utils/translator";

const tourism = {
  tourism: {
    name: () => translate("Tourism"),
    icon: icons.castle,
    selectors: ["tourism=*"],
    synonyms: [
      "350-3500-0304",
      "350-3510-0236",
      "350-3510-0237",
      "350-3522-0239",
      "350-3550-0336",
      "500-5510-0374",
      "550-5510-0000",
      "550-5510-0349",
      "550-5510-0357",
      "550-5510-0358",
      "550-5510-0359",
      "550-5510-0382",
      "550-5510-0383",
      "550-5510-0384",
      "550-5510-0385",
      "700-7460-0115",
      "900-9200-0000",
      "900-9200-0301",
      "Bicycle Trailhead",
      "Bike Trail",
      "Conference",
      "Convention",
      "Cross-country Skiing Trailhead",
      "Hiking Trailhead",
      "Horse Riding Trailhead",
      "Luggage Store",
      "Mountain Bike Trailhead",
      "Mountain Pass",
      "Nature Preserve",
      "Off-Road Vehicle Area",
      "Off-road Trailhead",
      "Pedestrian Plaza",
      "Rafting",
      "Summer Camp",
      "Tour Provider",
      "Tourismusinformationszentrum",
      "Tourist Information Center",
      "Tourist Information",
      "Trailhead",
      "Walking Path Trailhead",
      "tourism",
    ],
  },

  information: {
    name: () => translate("Information"),
    icon: icons.information,
    parents: ["tourism", "accommodation", "public_transfer"],
    selectors: [
      "information=audioguide",
      "information=board",
      "information=guidepost",
      "information=map",
      "information=stele",
      "information=terminal",
    ],
  },

  animal: {
    name: () => translate("Animal"),
    icon: icons.attraction,
    parents: ["tourism", "leisure"],
    selectors: ["attraction=animal"],
  },

  telephone: {
    name: () => translate("Telephone"),
    icon: icons.telephone,
    parents: ["tourism", "shopping", "public_transfer"],
    selectors: ["amenity=telephone"],
  },

  attraction: {
    name: () => translate("Tourist Attraction"),
    icon: icons.attraction,
    parents: ["tourism"],
    selectors: ["tourism=attraction"],
    synonyms: [
      "300-3000-0000",
      "300-3000-0023",
      "300-3000-0231",
      "300-3000-0232",
      "350-3500-0235",
      "Flyover",
      "Island Hot Spring",
      "Landmark or Attraction",
      "Lighthouse",
      "Palace",
      "Sehenswürdigkeit",
      "Tourist Attraction",
      "Volcano",
      "Waterfall",
      "attraction",
      "tourist_information_center",
    ],
  },

  memorial: {
    name: () => translate("Memorial"),
    icon: icons.historic,
    parents: ["tourism"],
    selectors: ["historic=memorial"],
    synonyms: [
      "300-3000-0025",
      "Historical Monument",
      "Memorial Site",
      "Monument / Landmark",
      "Monument",
      "monument",
    ],
  },

  viewpoint: {
    name: () => translate("Viewpoint"),
    icon: icons.viewpoint,
    parents: ["tourism"],
    selectors: ["tourism=viewpoint"],
    synonyms: [
      "350-3510-0238",
      "350-3520-0224",
      "400-4300-0308",
      "550-5510-0242",
      "900-9200-0386",
      "Aussichtspunkt",
      "Meeting Point",
      "Mountain Peak",
      "Scenic Area",
      "Scenic Lookout",
      "Undersea Feature",
      "Viewpoint",
      "Vineyard",
    ],
  },

  castle: {
    name: () => translate("Castle"),
    icon: icons.castle,
    parents: ["tourism"],
    selectors: ["historic=castle"],
    synonyms: ["Castle"],
  },

  beach: {
    name: () => translate("Beach"),
    icon: icons.beach,
    parents: ["tourism"],
    selectors: ["natural=beach"],
    synonyms: [
      "550-5510-0205",
      "550-5510-0243",
      "Bay",
      "Beach",
      "Nudist Beach",
      "Surf Life Savings Club",
      "Surf Spot",
      "beach_resort",
    ],
  },

  cave: {
    name: () => translate("Cave Entrance"),
    icon: icons.mountain,
    parents: ["tourism"],
    selectors: ["natural=cave_entrance"],
    synonyms: ["Cave", "cave_entrance"],
  },

  themepark: {
    name: () => translate("Theme Park"),
    icon: icons.playground,
    parents: ["tourism"],
    selectors: ["tourism=theme_park"],
    synonyms: [
      "550-5520-0000",
      "550-5520-0207",
      "Theme Park Ride / Attraction",
      "Theme Park or Holiday Camp",
      "Theme Park",
      "amusement_park",
      "theme_park",
    ],
  },

  archaeological_site: {
    name: () => translate("Archaeological Site"),
    icon: icons.historic,
    parents: ["tourism"],
    selectors: ["historic=archaeological_site"],
  },
} as const;

export function getTourism() {
  return tourism;
}
